namespace: rag-assistant

api:
  replicaCount: 1
  image:
    repository: ghcr.io/rssubhammohanty/rag-docs-ai-assistant
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8000
    targetPort: 8000
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"

streamlit:
  replicaCount: 1
  image:
    repository: ghcr.io/rssubhammohanty/rag-docs-ai-assistant
    tag: "1.4"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8501
    targetPort: 8501
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"

chroma:
  persistence:
    storageClass: standard
    accessMode: ReadWriteOnce
    size: 1Gi

ingestion:
  image:
    repository: ghcr.io/rssubhammohanty/rag-docs-ai-assistant
    tag: latest
    pullPolicy: Always
  resources:
    requests:
      cpu: "500m"
      memory: "2Gi"
    limits:
      cpu: "2"
      memory: "3Gi"

config:
  environment: kubernetes
  chromaPath: /app/chroma_db
