apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rag-assistant-chroma-pvc
  namespace: rag-assistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi