apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rag-assistant-ingress
  namespace: rag-assistant
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rag-assistant-streamlit
                port:
                  number: 8501