apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-assistant-api
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: rag-assistant-api
  template:
    metadata:
      labels:
        app: rag-assistant-api
    spec:
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: rag-assistant-secret
                  key: API_KEY
            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: rag-assistant-secret
                  key: GROQ_API_KEY
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: rag-assistant-config
                  key: ENVIRONMENT
            - name: CHROMA_PATH
              valueFrom:
                configMapKeyRef:
                  name: rag-assistant-config
                  key: CHROMA_PATH
          resources:
{{ toYaml .Values.api.resources | nindent 12 }}
          startupProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 18
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: chroma-storage
              mountPath: /app/chroma_db
      volumes:
        - name: chroma-storage
          persistentVolumeClaim:
            claimName: rag-assistant-chroma-pvc
