apiVersion: v1
kind: Service
metadata:
  name: rag-assistant-api
  namespace: {{ .Values.namespace }}
  labels:
    app: rag-assistant-api
spec:
  selector:
    app: rag-assistant-api
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
  type: {{ .Values.api.service.type }}