apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rag-assistant-chroma-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - {{ .Values.chroma.persistence.accessMode }}
  storageClassName: {{ .Values.chroma.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.chroma.persistence.size }}
