apiVersion: v1
kind: Secret
metadata:
  name: rag-assistant-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  API_KEY: {{ required "secrets.apiKey is required" .Values.secrets.apiKey | quote }}
  GROQ_API_KEY: {{ required "secrets.groqApiKey is required" .Values.secrets.groqApiKey | quote }}