apiVersion: v1
kind: Service
metadata:
  name: rag-assistant-streamlit
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: rag-assistant-streamlit
  ports:
    - protocol: TCP
      port: {{ .Values.streamlit.service.port }}
      targetPort: {{ .Values.streamlit.service.targetPort }}
  type: {{ .Values.streamlit.service.type }}
